# Generated by Django 5.2.8 on 2025-12-12 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.TextField(
                default=12345, validators=[django.core.validators.MinLengthValidator(8)]
            ),
            preserve_default=False,
        ),
    ]
