# Generated by Django 5.2.8 on 2025-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0002_employee_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Оформлен"),
        ),
    ]
