# Generated by Django 5.2.8 on 2025-12-20 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("cart", "Корзина"), ("ordered", "Оформлен")],
                default="cart",
                max_length=20,
            ),
        ),
    ]
