# Generated by Django 5.2.8 on 2025-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0004_alter_order_order_date_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="for_whom",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
